### ISSUE TITLE
Need a license file in the repo

### ISSUE THREAD

**Issue by anandk266** [peppertech/OracleJET-Samples#1]
Hi JB. I am just planning to play with these. But it would help if there is a license file in the repo. I am sorry if I missed something.

**Comment by peppertech** [comment]
Hi @anandk266,

I can add a license file, but please note that most of the code here rather old. It may be better to look at my jsfiddle dashboard which has more up to date examples.

**Comment by peppertech** [comment]
https://jsfiddle.net/user/dashboard/

**Comment by peppertech** [comment]
Sorry, make that, https://jsfiddle.net/user/peppertech/fiddles/

**Comment by anandk266** [comment]
Thanks JB. I work for Oracle too :-) I will checkout your fiddles. I just
wanted to know what I can and cannot do with the code in OracleJet-Samples.

Anand

**Comment by peppertech** [comment]
I'm out for the Thanksgiving holiday break, but when I get back I will make
everything MIT. Do anything you like with the code. Just be aware of it's
age.

**Comment by anandk266** [comment]
Thanks JB.

Anand

**Comment by peppertech** [comment]
files added.  If a project is using Bower, it's out of date and should not be used as an example.  Fair warning.
